language: php

php: [5.6, 5.5, 5.4, hhvm]

install:
  - composer install --dev --prefer-source

script:
  - phpunit
  - vendor/bin/phpspec run -f pretty --no-interaction
  - ./vendor/bin/phpcs --standard=./vendor/drupal/coder/coder_sniffer/Drupal --ignore=./vendor --ignore=./doc --ignore=./spec .
